services:
  db:
    image: postgres:16-alpine
    container_name: budget_db
    environment:
      POSTGRES_DB: budget
      POSTGRES_USER: budget_admin
      POSTGRES_PASSWORD: budget1234
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5440:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U budget_admin -d budget" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: budgeting_site
    command: sh -c "sh /app/scripts/run.sh"
    volumes:
      - ../:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod
      - SECRET_KEY=c924tofl&x+y@d73!(3svrhf5o9+@f@z4i=0wok8^1cg4vpz=b
      - DB_USERNAME=budget_admin
      - DB_PASSWORD=budget1234
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=budget
      - DB_URL=postgres://budget_admin:budget1234@db:5432/budget
      - ACCESS_TOKEN_EXPIRE_MINUTES=30     # 30분
      - REFRESH_TOKEN_EXPIRE_MINUTES=1440  # 24시간
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data: